# site settings
title: kaalam.ai
subtitle: The Authors of Jazz
email: kaalam@kaalam.ai
description: Efficiency is never wrong.
baseurl: "/kaalam" # the subpath of your site, e.g. /blog
url: "https://kaalam.github.io" # the base hostname & protocol for your site
author: The Authors of Jazz
country: Madrid and the whole planet (for now).

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
github_url: https://github.com/kaalam
linkedin_url:
slack_url:
twitter_url: https://twitter.com/kaalam_ai

# build settings
markdown: kramdown

sass:
  style: compressed
