# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jazz News

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  Jazz related events for 2018.

baseurl: "/news" # the subpath of your site, e.g. /blog
url: "https://kaalam.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: kaalam.ai
twitter_username: kaalam_ai
github_username:  kaalam
company_name: kaalam.ai

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

